  ---
title: "HTE Notebook"
subtitle: "MissingValues-MICE"
authors: "Luiz Pinheiro, Hemerson Lucas, Matheus Matos, Guilherme Marra, João do IME"
output:
  html_document: default
  pdf_document: default
---
Load library and dataset

```{r}
library("mice")
library("dplyr")
pretreated_dataset <- read.csv("/home/mathews/Documents/unsurpevisedLearning/HTE/data/filteredAndTreatedData.csv", header = TRUE)
```

```{r}
#looking the dataset using mice, simple distribution of the missing data
md.pattern(pretreated_dataset)

#Checking for data missing bigger than 5%
pMiss <- function(x){sum(is.na(x))/length(x)*100}
apply(pretreated_dataset,2,pMiss)
apply(pretreated_dataset,1,pMiss)

init = mice(pretreated_dataset, maxit=0) 
predM = init$predictorMatrix

#Looks throught all the prediction methods of mice
#methods(mice)

#Some variables of our dataset are only control variables, it means they shouldn't be used for predictions, as for example the pacient id(X)
predM[,c("X")] = 0
predM[,c("Trauma.center")] = 0 #Should we not consider it???

#generating the data
m_ <- 5
tempData <- mice(pretreated_dataset, predictorMatrix=predM, m=m_,maxit=10,meth= "pmm",seed=500)


xyplot(tempData, ~ .R,pch=18,cex=1)

#looking for the new distribution of a specific variable
#xyplot(tempData, DBP.ph ~ X,pch=18,cex=1)

for (i in c(1:m_))
{
  completedData <- complete(tempData,i)
  write.csv(completedData, file=paste("/home/mathews/Documents/unsurpevisedLearning/HTE/data/MICE/MICE_pretreaned_dataset_",i,".csv", sep = ""))
}
```